llm:
  gpt_4o_mini: gpt-4o-mini-2024-07-18
  gpt_4o: gpt-4o-2024-08-06
  gemini_2_0_flash: gemini-2.0-flash-exp
  gemini_2_0_pro: gemini-2.0-pro-exp-02-05
  temperature: 0
retriever:
  headers_to_split_on:
    - ["#", "Header 1"]
    - ["##", "Header 2"]
  load_documents: False
  top_k: 3
  top_k_compression: 3
  ensemble_weights_: [0.3, 0.3, 0.4]
  ensemble_weights: [0.3]
  cohere_rerank_model: rerank-english-v3.0